image: buildpack-deps:latest

before_script:
  - mkdir /tmp/check
  - cd /tmp/check
  - curl -L https://github.com/libcheck/check/releases/download/0.12.0/check-0.12.0.tar.gz | tar xvz
  - cd check-0.12.0
  - ./configure
  - make
  - make check
  - make install
  - ldconfig # Refresh linker sources

stages:
  - build
  - test

build:
  stage: build
  script:
  - make
  artifacts:
    expire_in: 1 week
    paths:
    - bin/main

test:
  stage: test
  script:
  - make test
