image: debian:latest

before_script:
  - sudo apt-get install check

stages:
  - build
  - test

build:
  stage: build
  script:
  - make
  artifacts:
    expire_in: 1 week
    paths:
    - bin/main

test:
  stage: test
  script:
  - make test
