image: debian:latest

before_script:
  - apt-get update -y
  - apt-get install -y check

stages:
  - build
  - test

build:
  stage: build
  script:
  - make
  artifacts:
    expire_in: 1 week
    paths:
    - bin/main

test:
  stage: test
  script:
  - make test
