sudo: required

language: ruby

services:
- docker

before_install:
- docker pull sonna/check

script:
- docker run --rm -v $(pwd):/app -w /app sonna/check bash -c "make distclean; make"
- docker run --rm -v $(pwd):/app -w /app sonna/check bash -c "make testclean; make test"
