version: 2
jobs:
  build:
    docker:
    - image: sonna/check:latest
    steps:
    - checkout
    - run: make

  test:
    docker:
    - image: sonna/check:latest
    steps:
    - checkout
    - run: make test

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test
